Repository uddt-ds/EatsOkay, pull requests merged in 2025-06, with the labels that each got.

#16 [Docs] #15 - gitignore 수정
  .gitignore
Labels: documentation

#17 [Design] #13 - 디자인시스템 컬러 추가
  EatsOkay/Common/UIColor+.swift
Labels: design

#23 [Feat] #7 - 상세화면 mapView UI 구현
  EatsOkay/App/AppDelegate.swift
  EatsOkay/App/Assets.xcassets/currentLocationButton.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/currentLocationButton.imageset/Frame 1487724864.svg
  EatsOkay/App/Assets.xcassets/reloadButton.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/reloadButton.imageset/Swap 4.svg
  EatsOkay/App/SceneDelegate.swift
  EatsOkay/DetailViewController.swift
Labels: new feature

#24 [Feat] #1 - 상세화면 TableView UI 구현
  EatsOkay/App/Assets.xcassets/Detail/ChevronDown.imageset/ChevronDown.svg
  EatsOkay/App/Assets.xcassets/Detail/ChevronDown.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/Detail/Contents.json
  EatsOkay/App/Assets.xcassets/Detail/Rectangle.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/Detail/Rectangle.imageset/Rectangle.svg
  EatsOkay/App/Assets.xcassets/Detail/Star.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/Detail/Star.imageset/Star.svg
  EatsOkay/App/Assets.xcassets/Detail/Time.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/Detail/Time.imageset/Time.svg
  EatsOkay/Detail/DetailModel.swift
  EatsOkay/Detail/DetailTableViewCell.swift
  EatsOkay/Detail/DetailViewController.swift
Labels: new feature

#27 [Feat] #25 네트워크 매니저 구현, UserDefaults 매니저 구현
  EatsOkay/Service/GoogleAPI.swift
  EatsOkay/Service/GoogleMapResponse.swift
  EatsOkay/Service/KakaoAPI.swift
  EatsOkay/Service/KakaoResponse.swift
  EatsOkay/Service/NetworkManager.swift
  EatsOkay/Service/SearchTextBody.swift
  EatsOkay/Service/UserDeafaultsManager.swift
Labels: new feature

#29 [Feat] #28 스플래쉬 뷰 UI 구현
  EatsOkay/App/Assets.xcassets/splashBackground.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/splashBackground.imageset/splashBackground.svg
  EatsOkay/App/Assets.xcassets/splashLogo.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/splashLogo.imageset/splashLogo.svg
  EatsOkay/App/SceneDelegate.swift
  EatsOkay/Service/GoogleAPI.swift
  EatsOkay/Service/GoogleMapResponse.swift
  EatsOkay/Service/KakaoAPI.swift
  EatsOkay/Service/KakaoResponse.swift
  EatsOkay/Service/NetworkManager.swift
  EatsOkay/Service/SearchTextBody.swift
  EatsOkay/Service/UserDeafaultsManager.swift
  EatsOkay/SplashView/SplashViewController.swift
Labels: new feature

#46 [Feat] #12 - Detail Reactor 구현
  EatsOkay/App/Assets.xcassets/Detail/DefaultImage.imageset/Contents.json
  EatsOkay/App/Assets.xcassets/Detail/DefaultImage.imageset/DefaultImage.svg
  EatsOkay/Detail/DetailModel.swift
  EatsOkay/Detail/DetailReactor.swift
  EatsOkay/Detail/DetailTableViewCell.swift
  EatsOkay/Detail/DetailViewController.swift
  EatsOkay/Service/GoogleAPI.swift
  EatsOkay/Service/GoogleMapResponse.swift
  EatsOkay/Service/KakaoAPI.swift
  EatsOkay/Service/KakaoResponse.swift
  EatsOkay/Service/NetworkManager.swift
  EatsOkay/Service/SearchTextBody.swift
  EatsOkay/Service/UserDeafaultsManager.swift
Labels: new feature

#62 [Feat] KingFisher 사용하여 가게 이미지 바인딩
  EatsOkay/Detail/DetailReactor.swift
  EatsOkay/Detail/DetailTableViewCell.swift
  EatsOkay/Detail/DetailViewController.swift
  EatsOkay/Service/UserDeafaultsManager.swift
Labels: new feature

#72 [Fix] 실제기기 빌드에서 발생한 오류 수정
  EatsOkay.xcodeproj/project.pbxproj
  EatsOkay.xcodeproj/xcshareddata/xcschemes/EatsOkay.xcscheme
  EatsOkay/App/Info.plist
  EatsOkay/Common/UIColor+.swift
  EatsOkay/Common/UIComponent/CustomButton.swift
  EatsOkay/Common/UIComponent/CustomLocationAlert.swift
  EatsOkay/Detail/DetailModel.swift
  EatsOkay/Detail/DetailReactor.swift
  EatsOkay/Detail/DetailTableViewCell.swift
  EatsOkay/Detail/DetailViewController.swift
  EatsOkay/Service/LocationManager.swift
  EatsOkay/Service/LocationManager/LocationManager.swift
  EatsOkay/Service/LocationManager/LocationManagerError.swift
Labels: fix

#94 [Refactor] #93 - UserDefaultsManager
  EatsOkay/Detail/DetailReactor.swift
  EatsOkay/Detail/DetailViewController.swift
  EatsOkay/Home/HomeReactor.swift
  EatsOkay/LocationSelectView/LocationSelectReactor.swift
  EatsOkay/OnBoarding/OnBoardingReactor.swift
  EatsOkay/OnBoarding/OnBoardingViewController.swift
  EatsOkay/Service/UserDefaultsManager.swift
  EatsOkay/SplashView/SplashViewReactor.swift
Labels: enhancement

#96 [Feat] #95 - 라이트모드 고정, 회전 방지
  EatsOkay/App/AppDelegate.swift
  EatsOkay/App/Info.plist
Labels: new feature

#117 [Refactor] #109 - 가게 검색 로직 변경
  EatsOkay/Detail/DetailReactor.swift
  EatsOkay/Detail/DetailViewController.swift
Labels: enhancement

#118 [Feat] NetworkManager 수정 후 PR
  EatsOkay/Detail/DetailReactor.swift
  EatsOkay/Detail/DetailViewController.swift
  EatsOkay/Service/GoogleAPI.swift
  EatsOkay/Service/GoogleMapResponse.swift
  EatsOkay/Service/NetworkManager.swift
  EatsOkay/Service/SearchTextBody.swift
Labels: enhancement

#135 [Refactor] #132 - 온보딩VC 화면전환, 주석삭제
  EatsOkay/OnBoarding/OnBoardingViewController.swift
  EatsOkay/Service/GoogleAPI.swift
  EatsOkay/SplashView/SplashViewController.swift
Labels: enhancement

#139 [Feat] 공통 Separator 구현 및 적용
  EatsOkay/Common/UIComponent/CustomSeparator.swift
  EatsOkay/Detail/DetailTableViewCell.swift
  EatsOkay/Detail/DetailViewController.swift
Labels: new feature

#150 [Refactor] #129 - 디테일 화면 정렬 상태관리
  EatsOkay/Sources/Detail/Model/DetailModel.swift
  EatsOkay/Sources/Detail/Reactor/DetailReactor.swift
Labels: enhancement

#161 [Feat] #158 - CollectionView Compositional 기본 Layout 구현
  EatsOkay/Resources/Assets.xcassets/Summary/Contents.json
  EatsOkay/Resources/Assets.xcassets/Summary/WebIcon.imageset/Contents.json
  EatsOkay/Resources/Assets.xcassets/Summary/WebIcon.imageset/WebIcon.svg
  EatsOkay/Sources/Summary/View/CustomHeaderView.swift
  EatsOkay/Sources/Summary/View/SectionFourViewCell.swift
  EatsOkay/Sources/Summary/View/SectionOneViewCell.swift
  EatsOkay/Sources/Summary/View/SectionThreeViewCell.swift
  EatsOkay/Sources/Summary/View/SectionTwoViewCell.swift
  EatsOkay/Sources/Summary/View/SummaryViewController.swift
Labels: new feature
