Repository uddt-ds/EatsOkay, pull requests merged in 2025-07, with the labels that each got.

#176 [Feat] #162 - Summary View 섹션 1, 섹션 2 Cell 구현
  EatsOkay/Resources/Assets.xcassets/Summary/Call.imageset/Call.svg
  EatsOkay/Resources/Assets.xcassets/Summary/Call.imageset/Contents.json
  EatsOkay/Sources/Summary/Reactor/SummaryReactor.swift
  EatsOkay/Sources/Summary/View/SectionOneViewCell.swift
  EatsOkay/Sources/Summary/View/SectionTwoViewCell.swift
  EatsOkay/Sources/Summary/View/SummaryViewController.swift
Labels: new feature

#182 [Refactor] #181 - OnBoardingView 이미지 교체 및 애니메이션 추가
  EatsOkay/Resources/Assets.xcassets/OnBoarding/Contents.json
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding2.imageset/Contents.json
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding2.imageset/onBoarding21.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding2.imageset/onBoarding22.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding2.imageset/onBoarding23.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding3.imageset/Contents.json
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding3.imageset/onBoarding31.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding3.imageset/onBoarding32.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onBoarding3.imageset/onBoarding33.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onboarding1.imageset/Contents.json
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onboarding1.imageset/onBoarding11.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onboarding1.imageset/onBoarding12.png
  EatsOkay/Resources/Assets.xcassets/OnBoarding/onboarding1.imageset/onBoarding13.png
  EatsOkay/Resources/Assets.xcassets/onBoarding1.imageset/1onboarding1.png
  EatsOkay/Resources/Assets.xcassets/onBoarding1.imageset/1onboarding2.png
  EatsOkay/Resources/Assets.xcassets/onBoarding1.imageset/1onboarding3.png
  EatsOkay/Resources/Assets.xcassets/onBoarding2.imageset/2onboarding1.png
  EatsOkay/Resources/Assets.xcassets/onBoarding2.imageset/2onboarding2.png
  EatsOkay/Resources/Assets.xcassets/onBoarding2.imageset/2onboarding3.png
  EatsOkay/Resources/Assets.xcassets/onBoarding3.imageset/3onboarding1.png
  EatsOkay/Resources/Assets.xcassets/onBoarding3.imageset/3onboarding2.png
  EatsOkay/Resources/Assets.xcassets/onBoarding3.imageset/3onboarding3.png
  EatsOkay/Sources/OnBoarding/View/OnBoardingViewController.swift
Labels: enhancement

#188 [Feat] GoogleMapResponse 전화번호 추가
  EatsOkay/Sources/Service/NetworkManager/GoogleAPI.swift
  EatsOkay/Sources/Service/NetworkManager/GoogleMapResponse.swift
Labels: new feature

#192 [Feat] #184 - Summary View 섹션 2 데이터 바인딩
  EatsOkay/Resources/Assets.xcassets/Summary/Call2.imageset/Calll2.svg
  EatsOkay/Resources/Assets.xcassets/Summary/Call2.imageset/Contents.json
  EatsOkay/Sources/Common/Extension/OpeningHours+.swift
  EatsOkay/Sources/Detail/Model/DetailModel.swift
  EatsOkay/Sources/Detail/Reactor/DetailReactor.swift
  EatsOkay/Sources/Detail/View/DetailTableViewCell.swift
  EatsOkay/Sources/Summary/View/SectionTwoViewCell.swift
  EatsOkay/Sources/Summary/View/SummaryViewController.swift
Labels: new feature

#199 [Refactor] #194 - Summary View RxDataSource로 변경
  EatsOkay/Sources/Summary/Model/SummarySectionModel.swift
  EatsOkay/Sources/Summary/Reactor/SummaryReactor.swift
  EatsOkay/Sources/Summary/View/SectionOneViewCell.swift
  EatsOkay/Sources/Summary/View/SectionTwoViewCell.swift
  EatsOkay/Sources/Summary/View/SummaryViewController.swift
Labels: enhancement

#201 [Feat] #190 - SummaryView staticMap 구현
  EatsOkay/Resources/Assets.xcassets/closeIcon.imageset/Contents.json
  EatsOkay/Resources/Assets.xcassets/closeIcon.imageset/closeIcon.svg
  EatsOkay/Resources/Data/addressJSONData.json
  EatsOkay/Sources/Common/AttributedStringManager.swift
  EatsOkay/Sources/Common/Extension/UIColor+.swift
  EatsOkay/Sources/Detail/Reactor/DetailReactor.swift
  EatsOkay/Sources/Detail/View/DetailTableViewCell.swift
  EatsOkay/Sources/Detail/View/DetailViewController.swift
  EatsOkay/Sources/DetailPhotos/Model/DetailPhotos.swift
  EatsOkay/Sources/DetailPhotos/Model/DetailPhotosSectionOfCellModel.swift
  EatsOkay/Sources/DetailPhotos/Reactor/DetailPhotosReactor.swift
  EatsOkay/Sources/DetailPhotos/View/DetailPhotosViewController.swift
  EatsOkay/Sources/DetailPhotos/View/MainPhotosCell.swift
  EatsOkay/Sources/DetailPhotos/View/TotalPhotosCell.swift
  EatsOkay/Sources/Home/View/CardSectionsCell.swift
  EatsOkay/Sources/Home/View/HomeViewController.swift
  EatsOkay/Sources/Location/Reactor/LocationReactor.swift
  EatsOkay/Sources/Location/View/LocationViewController.swift
  EatsOkay/Sources/Service/AddressManager/AddressManager.swift
  EatsOkay/Sources/Service/AddressManager/MatchedLocationListData.swift
  EatsOkay/Sources/Service/NetworkManager/GoogleAPI.swift
  EatsOkay/Sources/Service/NetworkManager/NetworkManager.swift
  EatsOkay/Sources/Summary/Reactor/SummaryReactor.swift
  EatsOkay/Sources/Summary/View/CustomHeaderView.swift
  EatsOkay/Sources/Summary/View/SectionFourViewCell.swift
  EatsOkay/Sources/Summary/View/SummaryViewController.swift
Labels: new feature

#212 [Chore] #211 - Project 버전 수정
  Project.swift
Labels: chore

#216 [Fix] #215 - Detail View 코드 수정
  EatsOkay/Sources/Detail/Model/DetailModel.swift
  EatsOkay/Sources/Detail/Reactor/DetailReactor.swift
Labels: fix
